esp_toml_version = 1.0
firmware_images_url = "https://MichaelDu9226.github.io/Nous_Bootloader/bin/"

supported_apps = ["Nous_v3.0.1"]

[Nous_v3.0.1]
chipsets = ["ESP32S3"]
image.esp32s3 = "nous_v3.0.1_0x0_20250818.bin"
