esp_toml_version = 1.0
firmware_images_url = "https://ghproxy.net/https://raw.githubusercontent.com/MichaelDu9226/Nous_Bootloader/main/bin/"

supported_apps = ["TaleBot Pro_v.3.0.0"]

[TaleBot Pro_v.3.0.0]
chipsets = ["ESP32"]
image.esp32 = "talemap_v3.0.0_0x0_20250819.bin"
