esp_toml_version = 1.0
firmware_images_url = "https://MichaelDu9226.github.io/Nous_Bootloader/bin/"

supported_apps = ["Talemap"]

[Nous_Bootloader]
chipsets = ["ESP32S3"]
offset = "0x10000"
image.esp32s3 = "talemap_v3.0.2_0x10000_20250814.bin"
