esp_toml_version = 1.0
firmware_images_url = "https://MichaelDu9226.github.io/Nous_Bootloader/bin/"

supported_apps = ["Talemap"]

[Talemap]
chipsets = ["ESP32"]
image.esp32 = "talemap_v3.0.3_0x0_20250818.bin"
