esp_toml_version = 1.0
firmware_images_url = "https://MichaelDu9226.github.io/Nous_Bootloader/bin/"

supported_apps = ["TaleBot_Pro_v3_0_0"]

[TaleBot_Pro_v3_0_0]
chipsets = ["ESP32"]
image.esp32 = "talemap_0x0.bin"
